# Generated by Django 5.2.7 on 2025-10-23 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
        migrations.AlterModelOptions(
            name='candidatura',
            options={'verbose_name': 'Candidatura', 'verbose_name_plural': 'Candidaturas'},
        ),
        migrations.AlterModelOptions(
            name='coordenador',
            options={'verbose_name': 'Coordenador', 'verbose_name_plural': 'Coordenadores'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'Professor', 'verbose_name_plural': 'Professores'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterModelOptions(
            name='vagamonitoria',
            options={'verbose_name': 'Vaga de Monitoria', 'verbose_name_plural': 'Vagas de Monitoria'},
        ),
    ]
